name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.404
 
    - name: Build
      run: dotnet build Task1/blob/main/WebApplication2.sln
  
    - name: Test
      run: dotnet test Task1/blob/main/WebApplication2.sln   
