name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.403
 
    - name: Build
      run: dotnet build 'D:\a\Task1\Task1\WebApplication2\WebApplication2.sln'
    - name: Test
      run: dotnet test 'D:\a\Task1\Task1\WebApplication2\WebApplication2.sln'
    
    
