- name: Send mail

  if: always()

  uses: dawidd6/action-send-mail@v2

  with:

# mail server settings

    server_address: smtp.gmail.com

  server_port: 465

    username: ${{ secrets.EMAIL_USERNAME }}

    password: ${{ secrets.EMAIL_PASSWORD }}



# email subject

  subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}

# email body as text

  body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}

# comma-separated string, send email to

  to: kvranjitha24@gmail.com

# from email name

  from: ranjithareddy348@gmail.com
